### PR TITLE
Use `exportEvents` over manual buffering

### PR DESCRIPTION
**Pull request by macobo**
:wave: I work at PostHog

Latest versions of posthog support a new plugin method `exportEvents`
which makes data export plugins require less code and reduces reliability
issues.

This change moves this plugin over to the new pattern

Tested by installing the plugin on a local dev instance

cc @utsabc @saikumarrs 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Gauravudia** [comment]
@macobo In `manual buffering`, we were using the `retryable` logic for failed events. But this logic is now removed in this PR. So, how we are handling failed events retry with the new plugin method `exportEvents`?

**Comment by macobo** [comment]
Posthog handles retrying automatically from exportEvents the exact same way as the original code does but using less resources. As-is this plugin is relying on deprecated patterns and will cause reliability issues for rudderstack users.

**Review by Gauravudia — APPROVED** [review]

**Comment by ItsSudip** [comment]
Hey @macobo you have to sign [this](https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement) CLA to proceed further.

**Comment by macobo** [comment]
Done!

**Pull request merged**
